name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytest
    
    - name: Check Model Parameters
      run: |
        python -c "
        from src.model import MNISTModel
        model = MNISTModel()
        params = sum(p.numel() for p in model.parameters() if p.requires_grad)
        print(f'Model has {params} parameters')
        assert params < 25000, f'Model has too many parameters: {params}'
        "
    
    - name: Train model
      run: |
        python src/train.py
        ls -la models/  # List models directory contents
    
    - name: Run tests
      run: |
        pytest tests/ -v --capture=no  # Added --capture=no for more output
    
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        retention-days: 5

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          .pytest_cache/
          pytest-report.xml
        retention-days: 5